Registro:
    pattern:  /
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:index" }

Registro_index:
    pattern:  /
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:index" }

Registro_search:
    pattern:  /search
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:search" }

Registro_show:
    pattern:  /{id}/show
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:show" }

Registro_showperfil:
    pattern:  /{id}/showperfil
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:showperfil" }

Registro_new:
    pattern:  /new
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:new" }

Registro_create:
    pattern:  /create
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:create" }
    requirements: { _method: post }

Registro_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:edit" }

Registro_update:
    pattern:  /{id}/update
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:update" }
    requirements: { _method: post|put }

Registro_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TechTBundle:Tbdetusuariodatos:delete" }
    requirements: { _method: post|delete }


