EstatusUsuarios:
    pattern:  /
    defaults: { _controller: "TechTBundle:Tbgenestatusregistrousu:index" }

EstatusUsuarios_show:
    pattern:  /{id}/show
    defaults: { _controller: "TechTBundle:Tbgenestatusregistrousu:show" }

EstatusUsuarios_new:
    pattern:  /new
    defaults: { _controller: "TechTBundle:Tbgenestatusregistrousu:new" }

EstatusUsuarios_create:
    pattern:  /create
    defaults: { _controller: "TechTBundle:Tbgenestatusregistrousu:create" }
    requirements: { _method: post }

EstatusUsuarios_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TechTBundle:Tbgenestatusregistrousu:edit" }

EstatusUsuarios_update:
    pattern:  /{id}/update
    defaults: { _controller: "TechTBundle:Tbgenestatusregistrousu:update" }
    requirements: { _method: post|put }

EstatusUsuarios_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TechTBundle:Tbgenestatusregistrousu:delete" }
    requirements: { _method: post|delete }
