Parametro:
    pattern:  /
    defaults: { _controller: "TechTBundle:Tbgenparametros:index" }

Parametro_show:
    pattern:  /{id}/show
    defaults: { _controller: "TechTBundle:Tbgenparametros:show" }

Parametro_new:
    pattern:  /new
    defaults: { _controller: "TechTBundle:Tbgenparametros:new" }

Parametro_create:
    pattern:  /create
    defaults: { _controller: "TechTBundle:Tbgenparametros:create" }
    requirements: { _method: post }

Parametro_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TechTBundle:Tbgenparametros:edit" }

Parametro_update:
    pattern:  /{id}/update
    defaults: { _controller: "TechTBundle:Tbgenparametros:update" }
    requirements: { _method: post|put }

Parametro_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TechTBundle:Tbgenparametros:delete" }
    requirements: { _method: post|delete }
