index:
    pattern:  /
    defaults: { _controller: TechTBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: TechTBundle:Default:index }

erroracceso:
    pattern:  /erroracceso
    defaults: { _controller: TechTBundle:Default:erroracceso }

rifs:
    pattern:   /rifs
    defaults:  { _controller: TechTBundle:Default:rifs }

especs:
    pattern:   /especs
    defaults:  { _controller: TechTBundle:Default:especs }

detalls:
    pattern:   /detalls
    defaults:  { _controller: TechTBundle:Default:detalls }


confirmObra:
    pattern:  /confirmObra
    defaults:  { _controller: TechTBundle:Default:confirmObra}

confirmCotizacion:
    pattern:  /confirmCotizacion
    defaults:  { _controller: TechTBundle:Default:confirmCotizacion}

confirmObraIns:
    pattern:  /confirmObraIns
    defaults:  { _controller: TechTBundle:Default:confirmObraIns}

confirmObraRec:
    pattern:  /confirmObraRec
    defaults:  { _controller: TechTBundle:Default:confirmObraRec}

logout:
    pattern: /logout

forgotpass:
    pattern:  /forgotpass
    defaults: { _controller: "TechTBundle:Default:newforgot" }

createforgot:
    pattern:  /createforgot
    defaults: { _controller: "TechTBundle:Default:createforgot" }
    requirements: { _method: post }

TechTBundle_Registro:
    resource: "@TechTBundle/Resources/config/routing/tbdetusuariodatos.yml"
    prefix:   /Registro

TechTBundle_Roles:
    resource: "@TechTBundle/Resources/config/routing/tbgenrol.yml"
    prefix:   /Roles

TechTBundle_TiposRoles:
    resource: "@TechTBundle/Resources/config/routing/tbgentiporol.yml"
    prefix:   /TiposRoles

TechTBundle_Funciones:
    resource: "@TechTBundle/Resources/config/routing/tbgenfuncion.yml"
    prefix:   /Funciones

TechTBundle_Parametro:
    resource: "@TechTBundle/Resources/config/routing/tbgenparametros.yml"
    prefix:   /Parametros


TechTBundle_EstatusUsuarios:
    resource: "@TechTBundle/Resources/config/routing/tbgenestatusregistrousu.yml"
    prefix:   /EstatusUsuarios

TechTBundle_UsuarioAcceso:
    resource: "@TechTBundle/Resources/config/routing/tbdetusuarioacceso.yml"
    prefix:   /UsuarioAcceso


TechTBundle_RolesFunciones:
    resource: "@TechTBundle/Resources/config/routing/tbdetrolfuncion.yml"
    prefix:   /RolesFunciones


TechTBundle_ReporteLogin:
    resource: "@TechTBundle/Resources/config/routing/tblogconexion.yml"
    prefix:   /ReporteLogin

TechTBundle_Empresa:
    resource: "@TechTBundle/Resources/config/routing/tbdetempresa.yml"
    prefix:   /Empresa


TechTBundle_Contratos:
    resource: "@TechTBundle/Resources/config/routing/tbdetcontratorif.yml"
    prefix:   /Contratos


TechTBundle_UsuariosContratos:
    resource: "@TechTBundle/Resources/config/routing/tbdetusuariocontrato.yml"
    prefix:   /UsuariosContratos

TechTBundle_RegistroEstatus:
    resource: "@TechTBundle/Resources/config/routing/tblogestatususuario.yml"
    prefix:   /RegistroEstatus


TechTBundle_SolicitudServicio:
    resource: "@TechTBundle/Resources/config/routing/tbgensolicitudservicio.yml"
    prefix:   /SolicitudServicio




TechTBundle_Servicios:
    resource: "@TechTBundle/Resources/config/routing/tbgentiposolicitud.yml"
    prefix:   /Servicios

TechTBundle_Especificaciones:
    resource: "@TechTBundle/Resources/config/routing/tbgenespecsolicitud.yml"
    prefix:   /Especificaciones


TechTBundle_Detalles:
    resource: "@TechTBundle/Resources/config/routing/tbgendetalle.yml"
    prefix:   /Detalles

TechTBundle_CalidadPreguntas:
    resource: "@TechTBundle/Resources/config/routing/tbgencalidadservpreg.yml"
    prefix:   /CalidadPreguntas

TechTBundle_CalidadRespuestas:
    resource: "@TechTBundle/Resources/config/routing/tbgencalidadservresp.yml"
    prefix:   /CalidadRespuestas

TechTBundle_TipoSolCalidad:
    resource: "@TechTBundle/Resources/config/routing/tbdetreltiposolcalidadserv.yml"
    prefix:   /TipoSolCalidad

TechTBundle_PregResp:
    resource: "@TechTBundle/Resources/config/routing/tbgencalserpregcalserresp.yml"
    prefix:   /PregResp

TechTBundle_DetalleUsuario:
    resource: "@TechTBundle/Resources/config/routing/tbdetdetalleusuario.yml"
    prefix:   /DetalleUsuario

TechTBundle_CalidadServicio:
    resource: "@TechTBundle/Resources/config/routing/tbgensolservcalserv.yml"
    prefix:   /CalidadServicio

TechTBundle_EstadosSolicitud:
    resource: "@TechTBundle/Resources/config/routing/tbgenestatussolicitud.yml"
    prefix:   /EstadosSolicitud








TechTBundle_Formulario:
    resource: "@TechTBundle/Resources/config/routing/formulario.yml"
    prefix:   /Formulario

TechTBundle_PersonaPotencial:
    resource: "@TechTBundle/Resources/config/routing/personapotencial.yml"
    prefix:   /PersonaPotencial

TechTBundle_PersonaForm:
    resource: "@TechTBundle/Resources/config/routing/personarelform.yml"
    prefix:   /PersonaForm

TechTBundle_FormRel:
    resource: "@TechTBundle/Resources/config/routing/formulariorelacion.yml"
    prefix:   /FormRel

TechTBundle_Pregunta:
    resource: "@TechTBundle/Resources/config/routing/preguntaform.yml"
    prefix:   /Pregunta

TechTBundle_Respuesta:
    resource: "@TechTBundle/Resources/config/routing/respuestaform.yml"
    prefix:   /Respuesta

TechTBundle_PregResRel:
    resource: "@TechTBundle/Resources/config/routing/pregresprel.yml"
    prefix:   /PregResRel

TechTBundle_PersonaRespuestas:
    resource: "@TechTBundle/Resources/config/routing/personarespuesta.yml"
    prefix:   /PersonaRespuestas

TechTBundle_Tecnico:
    resource: "@TechTBundle/Resources/config/routing/tbdettecnico.yml"
    prefix:   /Tecnico

TechTBundle_Almacenista:
    resource: "@TechTBundle/Resources/config/routing/tbdetalmacenista.yml"
    prefix:   /Almacenista

TechTBundle_Cotizacion:
    resource: "@TechTBundle/Resources/config/routing/tbdetcotizacion.yml"
    prefix:   /Cotizacion

TechTBundle_Obra:
    resource: "@TechTBundle/Resources/config/routing/tbdetproyecto.yml"
    prefix:   /Obra

TechTBundle_EstatusCotizacion:
    resource: "@TechTBundle/Resources/config/routing/tbdetestatusinstalacion.yml"
    prefix:   /EstatusCotizacion

TechTBundle_EstatusObra:
    resource: "@TechTBundle/Resources/config/routing/tbdetestatusproyecto.yml"
    prefix: /EstatusObra

TechTBundle_Asignacion:
    resource: "@TechTBundle/Resources/config/routing/tbreltecnicoproyecto.yml"
    prefix:   /Asignacion

TBundle_AsignacionLider:
    resource: "@TechTBundle/Resources/config/routing/tbdetcoordinadorpmo.yml"
    prefix:   /AsignacionLider

TBundle_Lider:
    resource: "@TechTBundle/Resources/config/routing/tbdetliderpmo.yml"
    prefix:   /Lider

