index:
    pattern:  /
    defaults: { _controller: TechTBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: TechTBundle:Default:index }

rifs:
    pattern:   /rifs
    defaults:  { _controller: TechTBundle:Default:rifs }

logout:
     pattern: /logout

TechTBundle_Registro:
    resource: "@TechTBundle/Resources/config/routing/tbdetusuariodatos.yml"
    prefix:   /Registro

TechTBundle_Roles:
    resource: "@TechTBundle/Resources/config/routing/tbgenrol.yml"
    prefix:   /Roles

TechTBundle_TiposRoles:
    resource: "@TechTBundle/Resources/config/routing/tbgentiporol.yml"
    prefix:   /TiposRoles

TechTBundle_Funciones:
    resource: "@TechTBundle/Resources/config/routing/tbgenfuncion.yml"
    prefix:   /Funciones

TechTBundle_Parametro:
    resource: "@TechTBundle/Resources/config/routing/tbgenparametros.yml"
    prefix:   /Parametros


TechTBundle_EstatusUsuarios:
    resource: "@TechTBundle/Resources/config/routing/tbgenestatusregistrousu.yml"
    prefix:   /EstatusUsuarios

TechTBundle_UsuarioAcceso:
    resource: "@TechTBundle/Resources/config/routing/tbdetusuarioacceso.yml"
    prefix:   /UsuarioAcceso


TechTBundle_RolesFunciones:
    resource: "@TechTBundle/Resources/config/routing/tbdetrolfuncion.yml"
    prefix:   /RolesFunciones


TechTBundle_ReporteLogin:
    resource: "@TechTBundle/Resources/config/routing/tblogconexion.yml"
    prefix:   /ReporteLogin

TechTBundle_Empresa:
    resource: "@TechTBundle/Resources/config/routing/tbdetempresa.yml"
    prefix:   /Empresa


TechTBundle_Contratos:
    resource: "@TechTBundle/Resources/config/routing/tbdetcontratorif.yml"
    prefix:   /Contratos


TechTBundle_UsuariosContratos:
    resource: "@TechTBundle/Resources/config/routing/tbdetusuariocontrato.yml"
    prefix:   /UsuariosContratos

TechTBundle_RegistroEstatus:
    resource: "@TechTBundle/Resources/config/routing/tblogestatususuario.yml"
    prefix:   /RegistroEstatus


