Tech\TBundle\Entity\Personapotencial:
    type: entity
    table: PersonaPotencial
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vnombreCompleto:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vNOMBRE_COMPLETO
        vtelefono:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vTELEFONO
        vcorreoEmail:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vCORREO_EMAIL
        dfechaRegistro:
            type: datetime
            nullable: false
            comment: ''
            column: dFECHA_REGISTRO
    lifecycleCallbacks: {  }
