Tech\TBundle\Entity\Tbdetcoordinadorpmo:
    type: entity
    table: tbdetCoordinadorPMO
    indexes:
        fk_tbdetCoordinadorPMO_tbdetLiderPMO1:
            columns:
                - tbdetLiderPMO_id
        fk_tbdetCoordinadorPMO_tbdetUsuarioDatos1:
            columns:
                - tbdetUsuarioDatos_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valias:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        tbdetliderpmo:
            targetEntity: Tbdetliderpmo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbdetLiderPMO_id:
                    referencedColumnName: id
            orphanRemoval: false
        tbdetusuariodatos:
            targetEntity: Tbdetusuariodatos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbdetUsuarioDatos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
