Tech\TBundle\Entity\Tbdetproyecto:
    type: entity
    table: tbdetProyecto
    indexes:
        fk_tbdetProyecto_tbdetEstatusProyecto1:
            columns:
                - fk_tbdetEstatusProyecto_id
        fk_tbdetProyecto_Cot:
            columns:
                - fk_iCodCotizacion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        icodproyecto:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
            column: iCodProyecto
        fkIcodcotizacion:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: fk_iCodCotizacion
        icantidad:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        icantidadentregada:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: icantidadEntregada
    manyToOne:
        fkTbdetestatusproyecto:
            targetEntity: Tbdetestatusproyecto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_tbdetEstatusProyecto_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
