Tech\TBundle\Entity\Tbdetcotizacion:
    type: entity
    table: tbdetCotizacion
    indexes:
        fk_tbdetCotizacion_Cont:
            columns:
                - tbdetCotizacioncol
        fk_tbdetCotizacion_1:
            columns:
                - fk_iID_EstatusInstalacion
        fk_tbdetCotizacion_tbdetLiderPMO1:
            columns:
                - tbdetLiderPMO_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codcotizacion:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: codCotizacion
        dfecha:
            type: datetime
            nullable: false
            comment: ''
        dfechaIni:
            type: datetime
            nullable: false
            comment: ''
            column: dfecha_ini
        dfechaFin:
            type: datetime
            nullable: false
            comment: ''
            column: dfecha_fin
        iprioridad:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '5'
    manyToOne:
        fkIidEstatusinstalacion:
            targetEntity: Tbdetestatusinstalacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_EstatusInstalacion:
                    referencedColumnName: id
            orphanRemoval: false
        tbdetcotizacioncol:
            targetEntity: Tbdetcontratorif
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbdetCotizacioncol:
                    referencedColumnName: id
            orphanRemoval: false
        tbdetliderpmo:
            targetEntity: Tbdetliderpmo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbdetLiderPMO_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
