Tech\TBundle\Entity\Tbdetdetalleusuario:
    type: entity
    table: tbdetDetalleUsuario
    indexes:
        fk_iID_SOL_USU:
            columns:
                - fk_iID_SOL_USU
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vdetalle:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: vDETALLE
    manyToOne:
        fkIidSolUsu:
            targetEntity: Tbgensolicitudservicio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_SOL_USU:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
