Tech\TBundle\Entity\Tbdetrelalmacenisproyecto:
    type: entity
    table: tbdetrelAlmacenisProyecto
    indexes:
        fk_tbdetrelAlmacenisProyecto_1:
            columns:
                - fk_iID_tbdetProyecto_Alm
        fk_tbdetrelAlmacenisProyecto_2:
            columns:
                - fk_iID_tbdetAlmacenista
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dfecha:
            type: datetime
            nullable: false
            comment: ''
        fkIidEstatusalmacen:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: fk_iID_EstatusAlmacen
        vdescripcion:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    manyToOne:
        fkIidTbdetproyectoAlm:
            targetEntity: Tbdetproyecto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_tbdetProyecto_Alm:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidTbdetalmacenista:
            targetEntity: Tbdetalmacenista
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_tbdetAlmacenista:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
