Tech\TBundle\Entity\Tbdettecnico:
    type: entity
    table: tbdetTecnico
    indexes:
        fk_tbdetTecnico_1:
            columns:
                - fk_iID_USUA_DATOSTECN
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valias:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vAlias
    manyToOne:
        fkIidUsuaDatostecn:
            targetEntity: Tbdetusuariodatos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_USUA_DATOSTECN:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
