Tech\TBundle\Entity\Tbdetliderpmo:
    type: entity
    table: tbdetLiderPMO
    indexes:
        fk_tbdetLiderPMO_tbdetUsuarioDatos1:
            columns:
                - tbdetUsuarioDatos_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valias:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        tbdetusuariodatos:
            targetEntity: Tbdetusuariodatos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbdetUsuarioDatos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
