Tech\TBundle\Entity\Tbdetusuarioacceso:
    type: entity
    table: tbdetUsuarioAcceso
    indexes:
        CI:
            columns:
                - fk_iCI
        ID_ROL_idx:
            columns:
                - fk_iID_ROL
        ID_ESTATUS_idx:
            columns:
                - fk_iID_ESTATUS
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vclave:
            type: string
            nullable: true
            length: 7
            fixed: false
            comment: ''
            column: vCLAVE
    manyToOne:
        fkIidRol:
            targetEntity: Tbgenrol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ROL:
                    referencedColumnName: id
            orphanRemoval: false
        fkIci:
            targetEntity: Tbdetusuariodatos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iCI:
                    referencedColumnName: pk_iCI
            orphanRemoval: false
        fkIidEstatus:
            targetEntity: Tbgenestatusregistrousu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ESTATUS:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
