Tech\TBundle\Entity\Tbdetalmacenista:
    type: entity
    table: tbdetAlmacenista
    indexes:
        fk_tbdetAlmacenista_1:
            columns:
                - fk_iID_USUA_DATOSALM
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valias:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: vAlias
    manyToOne:
        fkIidUsuaDatosalm:
            targetEntity: Tbdetusuariodatos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_USUA_DATOSALM:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
