Tech\TBundle\Entity\Tbdetproyecto:
    type: entity
    table: tbdetProyecto
    indexes:
        fk_tbdetProyecto_tbdetEstatusProyecto1:
            columns:
                - fk_tbdetEstatusProyecto_id
        fk_tbdetProyecto_Cot:
            columns:
                - fk_iCodCotizacion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vdescripcion:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        icodproyecto:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
            column: iCodProyecto
        icantidad:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        icantidadentregada:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: icantidadEntregada
        icantidaddisponible:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: icantidadDisponible
        icantidadrecibida:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: icantidadRecibida
    manyToOne:
        fkTbdetestatusproyecto:
            targetEntity: Tbdetestatusproyecto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_tbdetEstatusProyecto_id:
                    referencedColumnName: id
            orphanRemoval: false
        fkIcodcotizacion:
            targetEntity: Tbdetcotizacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iCodCotizacion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
