Tech\TBundle\Entity\Tbgensolicitudservicio:
    type: entity
    table: tbgenSolicitudServicio
    indexes:
        fk_iID_USUA_DATOS:
            columns:
                - fk_iID_USUA_DATOS
        fk_iID_TIPO_SOL:
            columns:
                - fk_iID_ESP_SOL
        iID_CASO:
            columns:
                - iID_CASO
        fk_iID_Contrato:
            columns:
                - fk_iID_Contrato
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dfechaCreacion:
            type: datetime
            nullable: false
            comment: ''
            column: dFECHA_CREACION
        vdescEstatus:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: vdesc_Estatus
        dfechaCierre:
            type: datetime
            nullable: true
            comment: ''
            column: dFECHA_CIERRE
        iidCaso:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: iID_CASO
    manyToOne:
        fkIidContrato:
            targetEntity: Tbdetusuariocontrato
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_Contrato:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidUsuaDatos:
            targetEntity: Tbdetusuariodatos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_USUA_DATOS:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidEspSol:
            targetEntity: Tbgenespecsolicitud
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ESP_SOL:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
