Tech\TBundle\Entity\Tbgencalidadservpreg:
    type: entity
    table: tbgenCalidadServPreg
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vpregunta:
            type: string
            nullable: false
            length: 85
            fixed: false
            comment: ''
            column: vPREGUNTA
    lifecycleCallbacks: {  }
