Tech\TBundle\Entity\Tbgenestatusregistrousu:
    type: entity
    table: tbgenEstatusRegistroUsu
    uniqueConstraints:
        pk_iID_ESTATUS_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vdescripcion:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: vDESCRIPCION
    lifecycleCallbacks: {  }
