Tech\TBundle\Entity\Tbgendetalle:
    type: entity
    table: tbgenDetalle
    indexes:
        fk_iID_ESP_SOL:
            columns:
                - fk_iID_ESP_SOL
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vdescripcion:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            column: vDESCRIPCION
    manyToOne:
        fkIidEspSol:
            targetEntity: Tbgenespecsolicitud
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_ESP_SOL:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
