Tech\TBundle\Entity\Tbgentiposolicitud:
    type: entity
    table: tbgenTipoSolicitud
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vnombreTipoSol:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            column: vNOMBRE_TIPO_SOL
    lifecycleCallbacks: {  }
