Tech\TBundle\Entity\Tblogconexion:
    type: entity
    table: tblogConexion
    indexes:
        fk_iCI_idx:
            columns:
                - fk_iCI
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dfechaAcceso:
            type: datetime
            nullable: false
            comment: ''
            column: dFECHA_ACCESO
    manyToOne:
        fkIci:
            targetEntity: Tbdetusuariodatos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iCI:
                    referencedColumnName: pk_icedula
            orphanRemoval: false
    lifecycleCallbacks: {  }
