Tech\TBundle\Entity\Tbreltecnicoproyecto:
    type: entity
    table: tbrelTecnicoProyecto
    indexes:
        fk_tbrelTecnicoProyecto_1:
            columns:
                - fk_iID_tbdetTecnico
        fk_tbrelTecnicoCotizacion_2:
            columns:
                - fk_iID_tbdetCotizacion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dfecha:
            type: datetime
            nullable: false
            comment: ''
        vdescripcioncambioest:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: vdescripcionCambioEst
    manyToOne:
        fkIidTbdettecnico:
            targetEntity: Tbdettecnico
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_tbdetTecnico:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidTbdetcotizacion:
            targetEntity: Tbdetcotizacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_tbdetCotizacion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
