Tech\TBundle\Entity\Tbreltecnicoproyecto:
    type: entity
    table: tbrelTecnicoProyecto
    indexes:
        fk_tbrelTecnicoProyecto_1:
            columns:
                - fk_iID_tbdetTecnico
        fk_tbrelTecnicoProyecto_2:
            columns:
                - fk_iID_tbdetPRoyecto
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dfecha:
            type: datetime
            nullable: false
            comment: ''
        descripcioncambioest:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: descripcionCambioEst
    manyToOne:
        fkIidTbdettecnico:
            targetEntity: Tbdettecnico
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_tbdetTecnico:
                    referencedColumnName: id
            orphanRemoval: false
        fkIidTbdetproyecto:
            targetEntity: Tbdetproyecto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_iID_tbdetPRoyecto:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
